### ISSUE TITLE
Need a few clarification from freemius developers

### ISSUE THREAD

**Issue by swashata** [swashata/freemius-checkout-js#1]
### 1. POSTMESSAGE FROM FREEMIUS IFRAME

I assumed that postmessage coming from freemius iframes are always JSON encoded. They have a type and a data property. Hence I did something like this

https://github.com/swashata/freemius-checkout-js/blob/bb3afbd83d1a75a0176d7e05c9a847ecea59327b/src/lib/utils/postman.ts#L64-L72

### 2. CONFUSION AROUND FS.Postman.receiveOnce

While reverse engineering the `FS.Postman`, I realized that the method `FS.Postman.receiveOnce` actually just makes sure that no further callbacks can be added to the particular event type. It doesn't guarantee that the same callback will not be executed multiple times, given the iframe fires the same event multiple times.

You can check the implementation here

https://github.com/swashata/freemius-checkout-js/blob/bb3afbd83d1a75a0176d7e05c9a847ecea59327b/src/lib/utils/postman.ts#L88-L96

Maybe I have missed something. Your input on this is greatly appreciated.

### 3. IS THE FOLLOWING CHECK NECESSARY?

https://github.com/swashata/freemius-checkout-js/blob/bb3afbd83d1a75a0176d7e05c9a847ecea59327b/src/lib/utils/postman.ts#L43-L48

I think this is in the original code because the same JavaScript runs inside the iFrame too? IMO, I think this check is redundant and can be safe to remove, since we are already doing this

https://github.com/swashata/freemius-checkout-js/blob/bb3afbd83d1a75a0176d7e05c9a847ecea59327b/src/lib/utils/postman.ts#L50-L53

### 4. ACCEPTED QUERY PARAMETERS BY THE IFRAME

I have figured the following are the accepted GET parameters by the Freemius iFrame.

https://github.com/swashata/freemius-checkout-js/blob/bb3afbd83d1a75a0176d7e05c9a847ecea59327b/src/lib/checkout.ts#L378-L408

Please let me know if I have missed anything.

**Comment by vovafeldman** [comment]
Hey @swashata 👋

1. The JSON encoding and object structure are right.
2. The purpose of `FS.Postman.receiveOnce()` is indeed to make sure only one callback is **registered** for a given event type.
3. I don't recall the exact reason, but I guess it was needed if it's there. I think you are most likely right that with your implementation there's no need for it:
https://github.com/swashata/freemius-checkout-js/blob/bb3afbd83d1a75a0176d7e05c9a847ecea59327b/src/lib/utils/postman.ts#L50-L53
4. Every parameter that is available through the JS API (excluding callback handlers) is also available as a querystring param (url-encoded).

**Comment by swashata** [comment]
Thank you @vovafeldman, I will update with necessary changes as per your feedback.

Without sounding too nit-picky 😬, don't you think the `receiveOnce` would be better named `receiveOnly`!

**Comment by vovafeldman** [comment]
@swashata you're right, `receiveOnly` is probably a better name for this method.
